repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      # We might want to use lfs or remove the json files to enable these
      # - id: check-added-large-files
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: dart-format
        name: dart format
        entry: dart format lib test
        pass_filenames: false
        language: system

      - id: flutter-analyze
        name: flutter analyze
        entry: flutter analyze lib test
        pass_filenames: false
        language: system
