name: Continuous Integration Frontend

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build

      - name: Run Linters
        uses: pre-commit/action@v3.0.1

      - name: Run Unit Tests
        run: flutter test
